clang:
	clang-format -i src/*.cpp include/utils/*.h src/mspm/*.cpp src/nfpm/*.cpp include/mspm/*.h include/nfpm/*.h include/*.h include/test/*.h src/test/*.cpp ../software/src/*.cpp ../software/include/*.h
